spec_version: 2
description: hello world
 
environment:
  environment_name: env-labels-eac
  owner_email: shirel.m@quali.com
  state: active
#  labels:
#    key1: value1
    
inputs:
  agent:
    type: agent
    default: eks
 
outputs:
  hello-world:
    value: '{{ .grains.hello-world.outputs.hello_world }}'
  
grains:
  hello-world:
    kind: terraform
    spec:
      # provider-overrides:
      #   - name: aws3
      #     source: hashicorp/aws
      #     version: ~>5.30.0
      #     attributes:
      #       alias: ue1
      #       region: us-east-1
      #       assume_role:
      #         role_arn: arn:aws:iam::046086677675:role/some-role
      #   - name: aws2
      #     source: hashicorp/aws
      #     version: ~>5.20.0
      #     attributes:
      #       alias: uw2          
      #       region: us-west-2
      #       assume_role:
      #         role_arn: arn:aws:iam::046086677675:role/some-other-role
      source:
        store: test-spec2-public
        path: terraform/hello-world
      agent:
        name: '{{ .inputs.agent }}'
      inputs: 
      - vido: 'viddd'
      env-vars: []
      outputs:
      - hello_world
    tf-version: 1.5.5
